### ISSUE TITLE
报错  no match redis

### ISSUE THREAD

**Issue by gaoyan1998** [jeff-zou/flink-connector-redis#38]
用的是flink-connector-redis-1.2.7-jar-with-dependencies.jar flink1.15
sql:

create table sink_redis(user_key VARCHAR, field VARCHAR, inform VARCHAR) with (
  'connector' = 'redis',
  'host' = 'xxxx',
  'port' = 'xxxx',
  'password' = 'xxx',
  'database' = '8',
  'ttl' = '86400',
  --sink时key过期时间(秒)
  'command' = 'hset'
);

报错：
Caused by: java.lang.RuntimeException: no match redis
	at org.apache.flink.streaming.connectors.redis.common.hanlder.RedisHandlerServices.filterByContext(RedisHandlerServices.java:166)
	at org.apache.flink.streaming.connectors.redis.common.hanlder.RedisHandlerServices.filter(RedisHandlerServices.java:90)
	at org.apache.flink.streaming.connectors.redis.common.hanlder.RedisHandlerServices.findSingRedisHandler(RedisHandlerServices.java:76)
	at org.apache.flink.streaming.connectors.redis.common.hanlder.RedisHandlerServices.findRedisHandler(RedisHandlerServices.java:58)
	at org.apache.flink.streaming.connectors.redis.table.RedisDynamicTableSink.<init>(RedisDynamicTableSink.java:42)
	at org.apache.flink.streaming.connectors.redis.table.RedisDynamicTableFactory.createDynamicTableSink(RedisDynamicTableFactory.java:65)
	at org.apache.flink.table.factories.FactoryUtil.createDynamicTableSink(FactoryUtil.java:259)

**Comment by jeff-zou** [comment]
没有将jar包引入项目

gaoyan ***@***.***> 于2023年5月8日周一 18:36写道：

**Comment by jeff-zou** [comment]
是你项目没引入这个包

**Comment by gaoyan1998** [comment]
昂昂，我理解你的意思了，感谢感谢，我试试
